### ISSUE TITLE
Support Node.js v12

### ISSUE THREAD

**Issue by jaydenseric** [node-fetch/fetch-blob#98]
Currently, only Node.js v14+ is supported:

https://github.com/node-fetch/fetch-blob/blob/4747497b52c0d2b7e360b2281e1b51b779fc333c/package.json#L28-L30

I didn't realize this when I tried to update to the latest version and ran into problems with optional chaining:

- https://github.com/jaydenseric/apollo-upload-client/runs/2801578005?check_suite_focus=true#step:4:45
- https://github.com/node-fetch/fetch-blob/blob/4747497b52c0d2b7e360b2281e1b51b779fc333c/index.js#L198

Many packages at the moment, including all of mine, support Node.js `^12.20 || >= 14.13`. E.g:

https://github.com/jaydenseric/apollo-upload-client/blob/e19deb9f1fc950f35a2f652c02135408bbe2a38a/package.json#L43-L45

This range supports most of the important Node.js ESM and package `exports` field features.

Until Node.js v12 is EOL we'll be stuck on the last `fetch-blob` version to support it; would you consider expanding the current level of support to accept Node.js `^12.20 || >= 14.13`?

**Comment by jimmywarting** [comment]
We made the decision to ditch commonjs for ESM. Guess we wasn't so thoughtful of selecting the right node versions. We have a PR in node fetch that changed the engine to ["node": "^12.20.0 || ^14.13.1 || >=16.0.0"](https://github.com/node-fetch/node-fetch/pull/1141/files#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R14)

Maybe should select the same range since that is all version that support ESM

Willing to make PR and change package.json to those version?

**Comment by jaydenseric** [comment]
`^12.20.0 || ^14.13.1 || >=16.0.0` is still too high, and would result in us having to semver major change our `^12.20 || >= 14.13` ranges in any packages consuming `fetch-blob`.

- `12.20.0` is fine.
- `14.13.1` should be `14.13.0`. The only reason you would specify the later patch version is if you use the `node:` namespace for builtin modules (which you currently are not).
- To my knowledge, there is no functional reason to skip v15.

**Comment by jimmywarting** [comment]
That's fine 

then maybe this can work?
`^12.20.0 || >14.13.0`

**Comment by jaydenseric** [comment]
You forgot the `=` in the `>=`, it should be: `^12.20 || >= 14.13` (or `^12.20.0 || >= 14.13.0` is the same thing if you prefer that style).
